[package]
name = "utils"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
chrono = { workspace = true }
serial_test = { workspace = true }

[lints]
workspace = true
