name: docker-image

# On push to master - left for testing
# on:
#   push:
#     branches:
#       - "**" # target all branches
#   pull_request:
#     branches:
#       - master

on:
  schedule:
    - cron: "0 2 * * *" # 5 AM UTC daily

jobs:
  push_image_from_ubuntu:
    env:
      DOCKER_USERNAME: ${{ github.actor }}
      DOCKER_PASSWORD: ${{ secrets.GHCR_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0 # ensures that all tags are fetched

      - name: Checkout latest version tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          echo "Checking out $LATEST_TAG"
          git checkout "$LATEST_TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push docker image
        run: bash docker/image-snap-sync/build-and-push.sh
